spring:
  application:
    name: "dca-registry-service"

security:
  licensed-apps:
    - local-postman
    - dev
  licensed-internal-apps:
    - internal

aws:
  dynamodb:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    table: "invoice"
    keys:
      access: "test"
      secret: "test"